{
  "openapi" : "3.0.0",
  "info" : {
    "description" : "API definition for USP's restaurants.  This isn't an official resource. It was created by the Jopiter team as a tool to help integration with USP's poor and unopened API. We did a lot of digging on how it works so you don't have to. <br /> <br /> The original API was extracted from USP's Restaurant's APP ([Cardápio USP](https://play.google.com/store/apps/details?id=br.usp.cardapio_usp)). <br /> At the current version, the decompiled `HASH` is `596df9effde6f877717b4e81fdb2ca9f`.  It's used for all authentication within USP's APIs. Whenever (and if) it's changed, this page will be updated accordingly.",
    "license" : {
      "name" : "Apache-2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0"
    },
    "title" : "USP Restaurants API",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "description" : "USP Prod. Server",
    "url" : "https://uspdigital.usp.br/rucard/servicos"
  } ],
  "paths" : {
    "/restaurants" : {
      "post" : {
        "requestBody" : {
          "$ref" : "#/components/requestBodies/USPAuthBody"
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Example1" : {
                    "$ref" : "#/components/examples/RestaurantExample"
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/Restaurant"
                }
              }
            },
            "description" : "Default response"
          },
          "500" : {
            "description" : "Error if a bad hash was passed on request"
          }
        },
        "summary" : "Lists all restaurants"
      }
    },
    "/menu/{restaurant_id}" : {
      "post" : {
        "description" : "The {restaurant_id} can be found in the /restaurants API path, which contains all IDs for all restaurants from each campus.",
        "parameters" : [ {
          "description" : "Numeric ID for a specific restaurant. Can be found in /restaurants",
          "explode" : false,
          "in" : "path",
          "name" : "restaurant_id",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "style" : "simple"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/USPAuthBody"
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Example1" : {
                    "$ref" : "#/components/examples/MenuExample"
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/Menu"
                }
              }
            },
            "description" : "Default response"
          },
          "500" : {
            "description" : "Error if a bad hash was passed on request"
          }
        },
        "summary" : "Fetch menus by Restaurant ID"
      }
    }
  },
  "components" : {
    "examples" : {
      "RestaurantExample" : {
        "summary" : "Restaurant Example",
        "value" : {
          "name" : "Cidade Universitária",
          "restaurants" : [ {
            "alias" : "Central",
            "address" : "Praça do Relógio Solar, travessa 8, no 300, Campus Butantã, São Paulo - SP",
            "name" : "Central",
            "phones" : "(11) 3091-3318",
            "id" : "6",
            "latitude" : "-23.5602110",
            "longitude" : "-46.7218170",
            "photourl" : "https://uspdigital.usp.br/comumwebdev/imagens/cardapio/central.jpg",
            "workinghours" : {
              "sunday" : {
                "lunch" : "",
                "breakfast" : "",
                "dinner" : ""
              },
              "saturday" : {
                "lunch" : "11:15 às 14:15",
                "breakfast" : "07:30 às 09:00",
                "dinner" : ""
              },
              "weekdays" : {
                "lunch" : "11:15 às 14:15",
                "breakfast" : "07:00 às 08:30",
                "dinner" : "17:30 às 19:45"
              }
            },
            "cashiers" : [ {
              "address" : "Rua do Anfiteatro, nº 295 - Cidade Universitária - São Paulo - CEP 05508-060",
              "prices" : {
                "special" : {
                  "dinner" : "10,00",
                  "lunch" : "10,00",
                  "breakfast" : ""
                },
                "students" : {
                  "dinner" : "2,00",
                  "lunch" : "2,00",
                  "breakfast" : ""
                },
                "visiting" : {
                  "dinner" : "15,00",
                  "lunch" : "15,00",
                  "breakfast" : ""
                },
                "employees" : {
                  "dinner" : "15,00",
                  "lunch" : "15,00",
                  "breakfast" : ""
                }
              },
              "longitude" : "-46.7216980",
              "latitude" : "-23.5594340",
              "workinghours" : "Segunda à Sexta - 7h as 19h45"
            } ],
            "hasCashier" : "false"
          } ]
        }
      },
      "MenuExample" : {
        "summary" : "Menu Example",
        "value" : {
          "message" : {
            "error" : false,
            "message" : ""
          },
          "meals" : [ {
            "dinner" : {
              "menu" : "Acompanhamentos: Arroz / Feijão / Arroz Integral\nPrato principal: Isca de Carne à Moda Chinesa\nPrato principal Vegetariano: Cuscuz de Lentilha\nGuarnição: Macarrão Alho e Óleo\nSaladas: Alface, Tomate, Beterraba Cozida\nSobremesa: Laranja / Suco: Maracujá",
              "calories" : "1056"
            },
            "lunch" : {
              "menu" : "Acompanhamentos: Arroz / Feijão / Arroz Integral\nPrato principal: Frango Assado\nPrato principal Vegetariano: Ovo Frito\nGuarnição: Polenta\nSaladas: Alface, Pepino com Cenoura, Soja em Grãos\nSobremesa: Laranja / Suco: Maracujá",
              "calories" : "1219"
            },
            "date" : "09/03/2020"
          }, {
            "dinner" : {
              "menu" : "Acompanhamentos: Arroz / Feijão / Arroz Integral\nPrato principal: Hambúrguer Assado\nPrato principal Vegetariano: Hambúrguer de PTS (Contém Glúten)\nGuarnição: Cebola Agridoce\nSaladas: Alface, Pepino, Tomate \nSobremesa: Doce de Abobora Industrializado / Suc",
              "calories" : "895"
            },
            "lunch" : {
              "menu" : "Acompanhamentos: Arroz / Feijão / Arroz Integral\nPrato principal: Fricassê de Frango (Contém Lactose)\nPrato principal Vegetariano: Ovo Cozido\nGuarnição: Cenoura Sauté\nSaladas: Alface, Rabanete Agridoce, Abobrinha Cozida\nSobremesa: Doce de Abobora Industri",
              "calories" : "1145"
            },
            "date" : "13/03/2020"
          }, {
            "dinner" : {
              "menu" : "",
              "calories" : "0"
            },
            "lunch" : {
              "menu" : "Acompanhamentos: Arroz / Feijão / Arroz Integral\nPrato principal: Bisteca Suína\nPrato principal Vegetariano: Ovo Frito\nGuarnição: Farofa de Couve\nSaladas: Alface, Repolho, Berinjela Cozida\nSobremesa: Mamão / Suco: Caju",
              "calories" : "1236"
            },
            "date" : "14/03/2020"
          }, {
            "dinner" : {
              "menu" : "",
              "calories" : "0"
            },
            "lunch" : {
              "menu" : "",
              "calories" : "0"
            },
            "date" : "15/03/2020"
          } ],
          "observation" : {
            "observation" : "Cardápio sujeito a alteração sem aviso prévio"
          }
        }
      }
    },
    "requestBodies" : {
      "USPAuthBody" : {
        "content" : {
          "application/x-www-form-urlencoded" : {
            "schema" : {
              "$ref" : "#/components/schemas/USPAuthForm"
            }
          }
        },
        "description" : "USP request body for authentication",
        "required" : true
      }
    },
    "schemas" : {
      "USPAuthForm" : {
        "properties" : {
          "hash" : {
            "type" : "string"
          }
        },
        "required" : [ "hash" ],
        "type" : "object"
      },
      "Restaurant" : {
        "example" : {
          "name" : "name",
          "restaurants" : [ {
            "photourl" : "photourl",
            "hasCashier" : true,
            "address" : "address",
            "latitude" : "latitude",
            "name" : "name",
            "cashiers" : [ {
              "address" : "address",
              "latitude" : "latitude",
              "workinghours" : "workinghours",
              "prices" : {
                "special" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "visiting" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "students" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "employees" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                }
              },
              "longitude" : "longitude"
            }, {
              "address" : "address",
              "latitude" : "latitude",
              "workinghours" : "workinghours",
              "prices" : {
                "special" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "visiting" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "students" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "employees" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                }
              },
              "longitude" : "longitude"
            } ],
            "alias" : "alias",
            "phones" : "phones",
            "id" : "id",
            "workinghours" : {
              "sunday" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "saturday" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "weekdays" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              }
            },
            "longitude" : "longitude"
          }, {
            "photourl" : "photourl",
            "hasCashier" : true,
            "address" : "address",
            "latitude" : "latitude",
            "name" : "name",
            "cashiers" : [ {
              "address" : "address",
              "latitude" : "latitude",
              "workinghours" : "workinghours",
              "prices" : {
                "special" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "visiting" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "students" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "employees" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                }
              },
              "longitude" : "longitude"
            }, {
              "address" : "address",
              "latitude" : "latitude",
              "workinghours" : "workinghours",
              "prices" : {
                "special" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "visiting" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "students" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                },
                "employees" : {
                  "lunch" : "lunch",
                  "breakfast" : "breakfast",
                  "dinner" : "dinner"
                }
              },
              "longitude" : "longitude"
            } ],
            "alias" : "alias",
            "phones" : "phones",
            "id" : "id",
            "workinghours" : {
              "sunday" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "saturday" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "weekdays" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              }
            },
            "longitude" : "longitude"
          } ]
        },
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "restaurants" : {
            "items" : {
              "$ref" : "#/components/schemas/Restaurant_restaurants"
            },
            "type" : "array"
          }
        },
        "type" : "object"
      },
      "Menu" : {
        "example" : {
          "observation" : {
            "observation" : "observation"
          },
          "message" : {
            "message" : "message",
            "error" : true
          },
          "meals" : [ {
            "date" : "2000-01-23",
            "lunch" : {
              "calories" : "calories",
              "menu" : "menu"
            },
            "dinner" : {
              "calories" : "calories",
              "menu" : "menu"
            }
          }, {
            "date" : "2000-01-23",
            "lunch" : {
              "calories" : "calories",
              "menu" : "menu"
            },
            "dinner" : {
              "calories" : "calories",
              "menu" : "menu"
            }
          } ]
        },
        "properties" : {
          "message" : {
            "$ref" : "#/components/schemas/Menu_message"
          },
          "meals" : {
            "items" : {
              "$ref" : "#/components/schemas/Menu_meals"
            },
            "type" : "array"
          },
          "observation" : {
            "$ref" : "#/components/schemas/Menu_observation"
          }
        },
        "type" : "object"
      },
      "Restaurant_workinghours_sunday" : {
        "example" : {
          "lunch" : "lunch",
          "breakfast" : "breakfast",
          "dinner" : "dinner"
        },
        "properties" : {
          "lunch" : {
            "type" : "string"
          },
          "dinner" : {
            "type" : "string"
          },
          "breakfast" : {
            "type" : "string"
          }
        }
      },
      "Restaurant_workinghours" : {
        "example" : {
          "sunday" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          },
          "saturday" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          },
          "weekdays" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          }
        },
        "properties" : {
          "sunday" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          },
          "saturday" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          },
          "weekdays" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          }
        }
      },
      "Restaurant_prices" : {
        "example" : {
          "special" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          },
          "visiting" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          },
          "students" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          },
          "employees" : {
            "lunch" : "lunch",
            "breakfast" : "breakfast",
            "dinner" : "dinner"
          }
        },
        "properties" : {
          "special" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          },
          "students" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          },
          "visiting" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          },
          "employees" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours_sunday"
          }
        }
      },
      "Restaurant_cashiers" : {
        "example" : {
          "address" : "address",
          "latitude" : "latitude",
          "workinghours" : "workinghours",
          "prices" : {
            "special" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            },
            "visiting" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            },
            "students" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            },
            "employees" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            }
          },
          "longitude" : "longitude"
        },
        "properties" : {
          "address" : {
            "type" : "string"
          },
          "prices" : {
            "$ref" : "#/components/schemas/Restaurant_prices"
          },
          "longitude" : {
            "type" : "string"
          },
          "latitude" : {
            "type" : "string"
          },
          "workinghours" : {
            "type" : "string"
          }
        }
      },
      "Restaurant_restaurants" : {
        "example" : {
          "photourl" : "photourl",
          "hasCashier" : true,
          "address" : "address",
          "latitude" : "latitude",
          "name" : "name",
          "cashiers" : [ {
            "address" : "address",
            "latitude" : "latitude",
            "workinghours" : "workinghours",
            "prices" : {
              "special" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "visiting" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "students" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "employees" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              }
            },
            "longitude" : "longitude"
          }, {
            "address" : "address",
            "latitude" : "latitude",
            "workinghours" : "workinghours",
            "prices" : {
              "special" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "visiting" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "students" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              },
              "employees" : {
                "lunch" : "lunch",
                "breakfast" : "breakfast",
                "dinner" : "dinner"
              }
            },
            "longitude" : "longitude"
          } ],
          "alias" : "alias",
          "phones" : "phones",
          "id" : "id",
          "workinghours" : {
            "sunday" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            },
            "saturday" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            },
            "weekdays" : {
              "lunch" : "lunch",
              "breakfast" : "breakfast",
              "dinner" : "dinner"
            }
          },
          "longitude" : "longitude"
        },
        "properties" : {
          "alias" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "phones" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "latitude" : {
            "type" : "string"
          },
          "longitude" : {
            "type" : "string"
          },
          "photourl" : {
            "type" : "string"
          },
          "workinghours" : {
            "$ref" : "#/components/schemas/Restaurant_workinghours"
          },
          "cashiers" : {
            "items" : {
              "$ref" : "#/components/schemas/Restaurant_cashiers"
            },
            "type" : "array"
          },
          "hasCashier" : {
            "type" : "boolean"
          }
        }
      },
      "Menu_message" : {
        "example" : {
          "message" : "message",
          "error" : true
        },
        "properties" : {
          "message" : {
            "type" : "string"
          },
          "error" : {
            "type" : "boolean"
          }
        }
      },
      "Menu_dinner" : {
        "example" : {
          "calories" : "calories",
          "menu" : "menu"
        },
        "properties" : {
          "menu" : {
            "type" : "string"
          },
          "calories" : {
            "nullable" : true,
            "type" : "string"
          }
        }
      },
      "Menu_meals" : {
        "example" : {
          "date" : "2000-01-23",
          "lunch" : {
            "calories" : "calories",
            "menu" : "menu"
          },
          "dinner" : {
            "calories" : "calories",
            "menu" : "menu"
          }
        },
        "properties" : {
          "dinner" : {
            "$ref" : "#/components/schemas/Menu_dinner"
          },
          "lunch" : {
            "$ref" : "#/components/schemas/Menu_dinner"
          },
          "date" : {
            "format" : "date",
            "pattern" : "^\\d{2}\\/\\d{2}\\/\\d{4}$",
            "type" : "string"
          }
        }
      },
      "Menu_observation" : {
        "example" : {
          "observation" : "observation"
        },
        "properties" : {
          "observation" : {
            "type" : "string"
          }
        }
      }
    }
  }
}